services:
  mcpo:
    build: .
    container_name: ${CONTAINER_NAME:-mcpo-ui}
    restart: unless-stopped
    ports:
      - "${UI_PORT:-80}:80"
      - "${MCPO_PORT:-8000}:8000"
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-based MCP servers
    environment:
      - MCPO_API_KEY=${MCPO_API_KEY}
      - MCPO_BASE_URL=${MCPO_BASE_URL}
      - UI_USERNAME=${UI_USERNAME}
      - UI_PASSWORD_HASH=${UI_PASSWORD_HASH}
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:80/ && curl -f http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: mcpo-network
